on: [workflow_call]

name: libextism

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        pip install poetry
        pip install git+https://github.com/extism/cli
        extism install git
