on:
  workflow_dispatch:
  release:
    types:
      - released
name: Documentation
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Build Library and Docs
      run: make docs
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: ./doc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


